sudo: false
env:
- CXX=g++-4.8
language: node_js
node_js:
- '4.0'
- '4.1'
- '4.2'
deploy:
  provider: heroku
  on:
    branch: master
  app:
    master: pebblecode-cruk-api
  api_key:
    secure: doj8cFEb0ho/yURxFGbsfkyXMNHQ1y2qLC7J+KzuNyqTiakmiM5COtpHW+mKjW9tJojtlxnY4J/XAvp3H0VK3vuVfuT+i21P0lOITAloe0BjuZlcyP8rU8+Hwh8+juc9c5JLp6XWGLMj/nJnK9GRZq8Wd53WD9JKUKXc8zjc/bPhgMHOlSKtprpLmTFuzJPSFFETTRpLORGCGr00wTDyB6VG5mZqQE+OhNAi+pmMlkjb3GbMWWeKyGYX9WPirlL8VJKE0hwkOTlvi88h3s+KW9FRnJdFcS0mLqhGZgepmzCojIa3KRWaz1mLKajtC/baxUsR5WilpOyXFS98RmoD80XhZBy+uiF05+Pc2EWK4X4tSuEAzExxvszebxAnMg4st0ZHQ/vVfZW0GkV5QuBqidy9aAoKv0ESO0htsYt91kecoN6V9HcIz0C19hg65xPEuS73Ck2k2RHmyTO+C6lhy6AtpBqK9PUPA6y94DmRO3CxCy/2Q+hyZU7UYyYPcC1ahukT/QkmRVIwlwivrcL85c67pE5Id4ecTTZr0iyox0coQc8cOHUOkjXUmLMXKOucjnS/Y+M5GOFwio3CJrjySe84VFFbU6Q5P9gUnAOvW2jDT49d4GkYGKK2MhsgA5zW78Q/mGVfYRqAFZd3Wc2hAYRe6QaiqAJD7aiJ53DpXVI=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
